"""
ai_analyzer.py – Sends collected data to Google Gemini and returns a markdown report.
"""

import asyncio
import logging
import textwrap
from datetime import date

import google.generativeai as genai
from config import settings

logger = logging.getLogger(__name__)

# Configure Gemini once at import time
genai.configure(api_key=settings.GEMINI_API_KEY)


SYSTEM_PROMPT = textwrap.dedent("""
    You are a senior trade & market analyst specializing in the Indian economy.
    You write clear, data-driven reports for investors, exporters, and policy makers.
    Always structure your output as clean Markdown.
""")

REPORT_TEMPLATE = textwrap.dedent("""
    You have been given recent news and market data about the **{sector}** sector in India.

    DATA COLLECTED ON: {date}

    === MARKET DATA & NEWS SNIPPETS ===
    {snippets_text}
    === END OF DATA ===

    Using ONLY the data above (and your general knowledge to fill gaps),
    generate a comprehensive Trade Opportunity Report in this EXACT Markdown structure:

    ---

    # 🇮🇳 India Trade Opportunity Report: {sector_title}
    **Report Date:** {date}
    **Sector:** {sector_title}

    ---

    ## 📊 Executive Summary
    (3-4 sentences summarising the current state and top opportunity)

    ## 📈 Market Overview
    - Current market size and growth rate
    - Key players (domestic + international)
    - India's global position in this sector

    ## 🚀 Top Trade Opportunities
    (List 4-6 specific, actionable trade opportunities with brief explanation each)

    ## 📦 Export Potential
    - Top export destinations for Indian {sector} goods/services
    - Competitive advantages India holds
    - Key products/services with highest demand

    ## 📥 Import Trends
    - What India imports in this sector and from where
    - Import substitution opportunities

    ## 🏛️ Government Policies & Incentives
    - Relevant schemes, PLI (Production Linked Incentive), or policies
    - Tax benefits, subsidies, or FDI rules

    ## ⚠️ Risks & Challenges
    (3-5 key risks investors/traders should be aware of)

    ## 🔮 6-12 Month Outlook
    (Forward-looking analysis with a bullish/neutral/bearish verdict and reasoning)

    ## 📰 Sources Used
    (List the news sources referenced from the data provided)

    ---
    *This report was auto-generated by the Trade Opportunities API.*
    *Always verify with official sources before making investment decisions.*

    ---
""")


class AIAnalyzer:
    """Generates a markdown report using Google Gemini."""

    def __init__(self):
        self.model = genai.GenerativeModel(
            model_name=settings.GEMINI_MODEL,
            system_instruction=SYSTEM_PROMPT,
        )

    async def generate_report(self, sector: str, market_data: dict) -> str:
        """
        Takes the collected market_data dict and returns a markdown string.
        """
        snippets_text = self._format_snippets(market_data.get("snippets", []))

        prompt = REPORT_TEMPLATE.format(
            sector=sector,
            sector_title=sector.title(),
            date=date.today().strftime("%B %d, %Y"),
            snippets_text=snippets_text,
        )

        logger.info("Sending prompt to Gemini (%d chars)…", len(prompt))

        loop = asyncio.get_event_loop()
        try:
            response = await loop.run_in_executor(
                None,
                lambda: self.model.generate_content(prompt)
            )
            report = response.text
            logger.info("Gemini returned %d chars.", len(report))
            return report

        except Exception as e:
            logger.error("Gemini API error: %s", e)
            # Fallback: return a basic report with the raw snippets
            return self._fallback_report(sector, market_data, str(e))

    def _format_snippets(self, snippets: list[dict]) -> str:
        lines = []
        for i, s in enumerate(snippets, 1):
            lines.append(
                f"{i}. **{s.get('title','(no title)')}**\n"
                f"   {s.get('body', '')}\n"
                f"   Source: {s.get('href', 'N/A')}\n"
            )
        return "\n".join(lines) if lines else "No recent data found."

    def _fallback_report(self, sector: str, market_data: dict, error: str) -> str:
        snippets_md = self._format_snippets(market_data.get("snippets", []))
        return textwrap.dedent(f"""
            # 🇮🇳 India Trade Opportunity Report: {sector.title()}

            > ⚠️ **Note:** AI analysis was unavailable ({error}).
            > The raw collected data is shown below for manual review.

            **Report Date:** {date.today()}

            ## Collected Market Data

            {snippets_md}

            ---
            *Trade Opportunities API – fallback mode*
        """)
